name: publish

on:
  push:
    tags:
      - 'v*'
env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.MAVEN_GPG_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
  GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
  GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
  IDEA_PUBLISH_TOKEN: ${{ secrets.IDEA_PUBLISH_TOKEN }}


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - id: get_version
        uses: battila7/get-version-action@v2.2.1

      - name: Set version
        run: echo "RELEASE_VERSION="${{ steps.get_version.outputs.version-without-v }} >> $GITHUB_ENV

      - name: Check version
        run: echo $RELEASE_VERSION

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish annotation core lib
        run: ./gradlew core:publishAllPublicationsToMavenCentralRepository --no-daemon --no-parallel

      - name: Publish compiler plugin
        run: ./gradlew compiler-plugin:publishAllPublicationsToMavenCentralRepository --no-daemon --no-parallel

      - name: Publish gradle plugin in maven central
        run: ./gradlew gradle-plugin:publishAllPublicationsToMavenCentralRepository --no-daemon --no-parallel

      - name: Publish gradle plugin in gradle portal
        run: ./gradlew gradle-plugin:publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET

      - name: Publish IDEA plugin
        run: ./gradlew idea-plugin:publishPlugin -Dorg.gradle.project.intellijPublishToken=$IDEA_PUBLISH_TOKEN

      - name: Publish release
        run: ./gradlew closeAndReleaseRepository --no-daemon --no-parallel