name: build

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Set version
        run: echo "RELEASE_VERSION=123" >> $GITHUB_ENV

      - name: Check version
        run: echo $RELEASE_VERSION

      - name: Check version2
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build