name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Get Version
        uses: battila7/get-version-action@v2.2.1

      - name: Check version
        run: |
          echo ${{ steps.get_version.outputs.version-without-v }} >> $GITHUB_ENV
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish annotation core lib
        run: ./gradlew core:publishMavenPublicationToMavenCentralRepository

      - name: Publish compiler plugin
        run: ./gradlew compiler-plugin:publishMavenPublicationToMavenCentralRepository

      - name: Publish gradle plugin
        run: ./gradlew gradle-plugin:publishMavenPublicationToMavenCentralRepository
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId:  ${{ secrets.MAVEN_GPG_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_GPG_PASSPHRASE }}